services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - ~/data:/var/lib/postgresql/data
  student-management:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: student-management
    environment:
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    ports:
      - "4000:4000"
    command: npm run start
    depends_on:
      - postgresdb